decibels_materiel_list:
    path:     /decibels/materiel/all
    defaults: { _controller: DecibelsMaterielBundle:Default:listMateriel }
    methods: [GET]

decibels_materiel_showOne:
    path:     /decibels/materiel/{id}
    defaults: { _controller: DecibelsMaterielBundle:Default:showOneMateriel }
    requirements:
        id: \d+
    methods: [GET]

decibels_materiel_add:
    path:     /decibels/materiel/ajouter
    defaults: { _controller: DecibelsMaterielBundle:Default:addMateriel }
    methods: [GET|POST]

decibels_materiel_edit:
    path:     /decibels/materiel/edit/{id}
    defaults: { _controller: DecibelsMaterielBundle:Default:editMateriel }
    requirements:
        id: \d+
    methods: [GET|POST]

decibels_materiel_delete:
    path:     /decibels/materiel/delete/{id}
    defaults: { _controller: DecibelsMaterielBundle:Default:deleteMateriel }
    requirements:
        id: \d+
    methods: [GET|POST]

