<?php

namespace Decibels\AchievementBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AchievementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AchievementRepository extends EntityRepository
{
	public function findAllSortByIdDesc()
	{
		$listAchievement = $this->createQueryBuilder('r')
							->orderBy('r.id', 'DESC')
							->getQuery()
							->getArrayResult();
							
		return $listAchievement;	
	}
}
