decibels_realisation:
    resource: "@DecibelsRealisationBundle/Resources/config/routing.yml"
    prefix:   /

decibels_common:
    resource: "@DecibelsCommonBundle/Resources/config/routing.yml"
    prefix:   /

decibels_equipement:
    resource: "@DecibelsEquipementBundle/Resources/config/routing.yml"
    prefix:   /

decibels_user:
    resource: "@DecibelsUserBundle/Resources/config/routing.yml"
    prefix:   /

decibels_news:
    resource: "@DecibelsNewsBundle/Resources/config/routing.yml"
    prefix:   /

