<?php

namespace Decibels\GeneralBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarrouselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarrouselRepository extends EntityRepository
{
    public function findAllActiveJoinFile() 
    {
        $listImage = $this->createQueryBuilder('c')
					 ->leftJoin('c.picture', 'p')
					 ->addSelect('p')
					 ->where('c.active = 1')
					 ->getQuery()
					 ->getResult();
		
		return $listImage;
    }
}
