<?php

namespace Decibels\NewsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
	public function findAllSortDate()
	{
		$qb = $this->createQueryBuilder('n');
		$qb->orderBy('n.date', 'DESC');
					
		return $qb->getQuery()->getResult();	
	}
	
	public function findWithComments($id)
	{
		$news = $this->createQueryBuilder('n')
					 ->leftJoin('n.comments', 'c')
					 ->addSelect('c')
					 ->where('n.id = :id')
					 ->setParameter('id', $id)
					 ->getQuery()
					 ->getSingleResult();
		
		return $news;
	}
}
