decibels_realisation_list:
    path:     /decibels/realisation
    defaults: { _controller: DecibelsAchievementBundle:FrontEnd:listAchievement }
    methods: [GET]

decibels_realisation_listAdmin:
    path:     /decibels/admin/realisation/list
    defaults: { _controller:DecibelsAchievementBundle:BackEnd:listAdmin }
    methods: [GET]

decibels_realisation_add:
    path:     /decibels/admin/realisation/add
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:addAchievement }
    methods: [GET|POST]

decibels_realisation_edit:
    path:     /decibels/admin/realisation/edit/{id}
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:editAchievement }
    requirements:
        id: \d+
    methods: [GET|POST]
        
decibels_realisation_delete:
    path:     /decibels/admin/realisation/delete/{id}
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:deleteAchievement }
    requirements:
        id: \d+
    methods: [GET|POST]
