decibels_achievement_list:
    path:     /decibels/achievement
    defaults: { _controller: DecibelsAchievementBundle:FrontEnd:listAchievement }
    methods: [GET]

decibels_achievement_listAdmin:
    path:     /decibels/admin/achievement/list
    defaults: { _controller:DecibelsAchievementBundle:BackEnd:listAdmin }
    methods: [GET]

decibels_achievement_add:
    path:     /decibels/admin/achievement/add
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:addAchievement }
    methods: [GET|POST]

decibels_achievement_edit:
    path:     /decibels/admin/achievement/edit/{id}
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:editAchievement }
    requirements:
        id: \d+
    methods: [GET|POST]
        
decibels_achievement_delete:
    path:     /decibels/admin/achievement/delete/{id}
    defaults: { _controller: DecibelsAchievementBundle:BackEnd:deleteAchievement }
    requirements:
        id: \d+
    methods: [GET|POST]
