decibels_login:
    path:     /decibels/login
    defaults: { _controller: DecibelsUserBundle:Default:login }
    methods: [GET]

decibels_login_check:
    path:     /decibels/logincheck
    defaults: { _controller: DecibelsUserBundle:Default:logincheck }
    methods: [GET]

decibels_logout:
    path:     /decibels/logout
    defaults: { _controller: DecibelsUserBundle:Default:logout }
    methods: [GET]
