decibels_realisation_list:
    path:     /decibels/realisation
    defaults: { _controller: DecibelsGeneralBundle:Default:index }
    methods: [GET]

decibels_realisation_add:
    path:     /decibels/realisation/add
    defaults: { _controller: DecibelsGeneralBundle:Default:addRealisation }
    methods: [GET|POST]

decibels_realisation_edit:
    path:     /decibels/realisation/edit/{id}
    defaults: { _controller: DecibelsGeneralBundle:Default:editRealisation }
    requirements:
        id: \d+
    methods: [GET|POST]
        
decibels_realisation_delete:
    path:     /decibels/realisation/delete/{id}
    defaults: { _controller: DecibelsGeneralBundle:Default:deleteRealisation }
    requirements:
        id: \d+
    methods: [GET|POST]

decibels_presentation:
    path:     /decibels/presentation
    defaults: { _controller: DecibelsGeneralBundle:Default:presentation }
    methods: [GET]
    
decibels_presentation_edit:
    path:     /decibels/presentation/edit
    defaults: { _controller: DecibelsGeneralBundle:Default:editPresentation }
    methods: [GET|POST]

decibels_contact:
    path:     /decibels/contact
    defaults: { _controller: DecibelsGeneralBundle:Default:contact }
    methods: [GET|POST]

decibels_admin_index:
    path:     /decibels/admin
    defaults: { _controller:DecibelsGeneralBundle:Default:admin }
    methods: [GET]

decibels_realisation_listAdmin:
    path:     /decibels/realisation/admin/list
    defaults: { _controller:DecibelsGeneralBundle:Default:listAdmin }
    methods: [GET]

decibels_file_uploadFile:
    path:     /decibels/file/upload
    defaults: { _controller:DecibelsGeneralBundle:Default:uploadFile }
    methods: [POST]
    
decibels_carrousel_addImage:
    path:     /decibels/carrousel/addImage
    defaults: { _controller:DecibelsGeneralBundle:Carrousel:addImage }
    methods: [GET|POST]

decibels_carrousel_changeImage:
    path:     /decibels/carrousel/changeImage
    defaults: { _controller:DecibelsGeneralBundle:Carrousel:changeImage }
    methods: [GET|POST]

decibels_carrousel_deleteImage:
    path:     /decibels/carrousel/deleteImage/{id}
    defaults: { _controller:DecibelsGeneralBundle:Carrousel:deleteImage }
    requirements:
        id: \d+
    methods: [GET|POST]
