<?php

namespace Decibels\RealisationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends EntityRepository
{
	public function findAllSortByIdDesc()
	{
		$listRealisation = $this->createQueryBuilder('r')
							->orderBy('r.id', 'DESC')
							->getQuery()
							->getArrayResult();
							
		return $listRealisation;	
	}
}
