decibels_news_show:
    path:     /show/{id}
    defaults: { _controller: "DecibelsNewsBundle:News:show" }
    methods: [GET]

decibels_news_new:
    path:     /new
    defaults: { _controller: "DecibelsNewsBundle:News:new" }
    methods: [GET|POST]

decibels_news_edit:
    path:     /edit/{id}
    defaults: { _controller: "DecibelsNewsBundle:News:edit" }
    methods: [GET|POST]

decibels_news_delete:
    path:     /delete/{id}
    defaults: { _controller: "DecibelsNewsBundle:News:delete" }
    methods: [GET|POST]

decibels_news_listAdmin:
    path:     /admin/list
    defaults: { _controller: "DecibelsNewsBundle:News:listAdmin" }
    methods: [GET]
