decibels_realisation_list:
    path:     /decibels/realisation
    defaults: { _controller: DecibelsRealisationBundle:FrontEnd:listRealisation }
    methods: [GET]

decibels_realisation_add:
    path:     /decibels/realisation/add
    defaults: { _controller: DecibelsRealisationBundle:BackEnd:addRealisation }
    methods: [GET|POST]

decibels_realisation_edit:
    path:     /decibels/realisation/edit/{id}
    defaults: { _controller: DecibelsRealisationBundle:BackEnd:editRealisation }
    requirements:
        id: \d+
    methods: [GET|POST]
        
decibels_realisation_delete:
    path:     /decibels/realisation/delete/{id}
    defaults: { _controller: DecibelsRealisationBundle:BackEnd:deleteRealisation }
    requirements:
        id: \d+
    methods: [GET|POST]
